version: 0.0
os: linux

hooks:

  BeforeInstall:
    - location: scripts/run_docker_commands.sh
      timeout: 300
      runas: root
 
 ApplicationStop:
    - location: scripts/removeimages.sh
      timeout: 300
      runas: root

    - location: scripts/removecontainer.sh
      timeout: 300
      runas: root