version: 0.0
os: linux

hooks:

  ApplicationStop:
    - location: scripts/removeimages.sh
      timeout: 300
      runas: root

    - location: scripts/removecontainer.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/run_docker_commands.sh
      timeout: 300
      runas: root

 