version: 0.0
os: linux

hooks:
  ApplicationStop:
   - location: scripts/docker_container_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root 

    - location: scripts/download_warfile.sh
      timeout: 300
      runas: root 

  ApplicationStart:
    - location: scripts/run_docker_commands.sh
      timeout: 300
      runas: root