version: 0.0
os: linux

files:
  - source: target/*.war 
    destination: /usr/local/tomcat/webapps/

hooks:

  ApplicationStop:

    - location: scripts/stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

    - location: scripts/removecontainer
      timeout: 300
      runas: root

    - location: scripts/removeimages
      timeout: 300
      runas: root

  ApplicationStart:
    
    - location: scripts/start_server
      timeout: 300
      runas: root

    - location: scripts/run_docker_commands
      timeout: 300
      runas: root

  

 