version: 0.0
os: linux

hooks:

  ApplicationStop:

    - location: scripts/removecontainer
      timeout: 300
      runas: root

    - location: scripts/removeimages
      timeout: 300
      runas: root

  BeforeInstall:
   
    - location: scripts/run_docker_commands
      timeout: 300
      runas: root


  

 
